CREATE TABLE gp_plant_gallery (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    search_category INTEGER NOT NULL,
    description TEXT NOT NULL,
    image TEXT NOT NULL,
    plant_type TEXT NOT NULL,
    sun TEXT NOT NULL,
    zones TEXT NOT NULL,
    soil TEXT NOT NULL
)
