INSERT INTO gp_plant_gallery (name, search_category, description, image, plant_type, sun, zones, soil)
VALUES
('Blueberries – Misty','2','Misty is one of the most attractive, vigorous and high yielding Southern Highbush varieties. The bright blue-green foliage provides a perfect contrast to the pink and white spring flowers and sky blue summer fruit. Yields best when planted with other varieties. Chilling needs are very low at 300 hours, but do not hesitate to plant it all the way to Seattle. One of the most popular varieties in California because of fast growth, high yields, consistent quality.','plant1.png','Perennial','Full Sun','Zones 5 to 10','Acidic, well-drained'),
('Strawberry – Alpine Mignonette','2','Exclusive French delicacy. This improved variety of easy to grow, compact perennial plants with dainty leaves produces sweet little pointed berries to savor all summer long.','plant2.png','Perennial','Full Sun/Partial Shade','Frost Hardy to Zone 5','Rich, well-drained'),
('Honey Crisp Apple Tree','2','Apples are generally late blooming. Need full sun, well-drained soil, and moderate fertility. Thin fruit to maximize quality and size. Susceptible to codling moth, apple scab, powdery mildew, and gophers. Requires a pollenizer. Empire, Gala, Granny Smith and Red Delicious are good choices. Three or more varieties are best. Harvest 3rd year.','plant3.png','n/a','Full Sun','Zones 3 to 8','Well-drained'),
('Bartlett Pear Tree','2','European pears are late blooming, tolerant of heavy wet soils, and a good choice for many areas. Susceptible to codling moth and some to fire blight. Plant at least two varieties for best results. Harvest 3rd year. Worlds most popular pear. Enticing sweet, aroma when the pear is ripe. Tolerates hot summers.','plant4.png','n/a','Full Sun','Zones 5 to 9','Loamy/Sandy'),
('Grapes – Black Monukka','2','Popular seedless variety for the home gardener. The hardiest of the European grape varieties with a long history of cultivation for wine and table use. Grapes are borne in long, loose, clusters. Good fresh or for raisins. Excellent used as an ornamental, for summer shade, arbors or leafy walls.','plant5.png','Perennial','Full Sun','Zones 6 – 11','Slightly acidic, well-drained, moderately fertile'),
('Lupine – Russell','1','Enjoy the beauty and hardiness of lupine. Tall flowers bloom in colors from purple to pink to yellow to white. Beautiful when planted in mass. Attracts hummingbirds and butterflies.','plant6.png','Perennial','Full Sun','Zones 3 to 9','Slightly acidic, well-drained'),
('Daffodils','1','Daffodils are a hardy and easy perennial that grows in most regions of North America, except in the hottest, wettest areas, such as South Florida. Daffodils are a fall-planted bulb, so plant them in autumn and they will bloom in late winter or early spring. The traditional daffodil flower may be a showy yellow or white, with six petals and a trumpet-shape central corona, but many cultivated varieties ("cultivars") exist today.','plant7.png','Perennial','Full Sun','Zones 3 to 8','Moderately fertile, well-drained'),
('Dutch Iris – White Wedgewood','1','The tall, beautiful iris, named after the Greek goddess who rode rainbows, comes in many magical colors. Despite its divine origins, this June bloomer is rugged, reliable, and easy to grow. A beautiful white Dutch iris to plant alone in a white garden, or mixed with other Dutch iris. White blossoms have accents of yellow at the throat. Good for attracting bees, butterflies, and to use as a cut flower.','plant8.png','Perennial','Full Sun/Partial Sun','Zones 4 to 9','Adaptable/Loamy/Sandy'),
('Marigold – African','1','No annual is more cheerful or easier to grow than the marigold. These flowers are the spendthrifts among annuals, bringing a wealth of gold, copper, and brass into our summer and autumn gardens. The flower popularity probably derives in part from its ability to bloom brightly all summer long.  Attracts bees and butterflies.','plant9.png','Annual','Full Sun','Zones 3 to 10','Moderately fertile, well-drained'),
('Sunflower – Lemon Queen','1','With bright blooms that go from mid-summer to early fall, sunflowers say "summer" like no other plant. Its scientific name comes from the Greek words helios ("sun") and anthos ("flower"). The flowers come in many colors (yellow, red, orange, maroon, brown) but they are commonly bright yellow with brown centers that ripen into heavy heads filled with seeds. Attracts bees and butterflies. Small, black seeds are favored by finches.','plant10.png','Annual','Full Sun','Zones 4 to 9','Adaptable to various, moderately fertile soil'),
('Basil – Genovese','3','There is nothing like the aroma of basil in the summer! Genovese has the traditional fragrance and flavor, making it excellent for almost any basil dish, especially pesto. One of the most useful herbs, it also has beautiful, edible flowers. In a warm, sunny window, basil can grow indoors in the winter! A good container variety. Attracts Bees/Butterflies.','plant11.png','Annual','Full Sun','Zones 5 to 10','Slightly acidic, well-drained, loamy'),
('Thyme – English','3','A short, compact, aromatic herb, thyme is a classic in any garden. It forms attractive, tiny lavender flowers which attract bees. Thyme adds interest to soups, casseroles, pizzas, and breads, and also has many medicinal uses.','plant12.png','Perennial','Full Sun/Partial Sun','Zones 5 to 9','Loamy/Sandy'),
('Oregano – Greek','3','Oregano is a perennial herb with rose-purple or white flowers and a taste reminiscent of thyme. Oregano’s taste is zesty and strong and is commonly used in Italian dishes. It is a hardy plant and makes for a good ground cover.','plant13.png','Perennial','Full Sun','Zones 5 to 10','Loamy'),
('Rosemary','3','A favorite in herb gardens everywhere, this woody and aromatic perennial herb has a distinctive flavor and scent with a multitude of medicinal and culinary purposes. Rosemary is also a great choice for ornamental plantings or containers. Rosemary is often trained as a topiary. Attracts Bees and Butterflies.','plant14.png','Perennial','Full Sun','Zones 7 to 11','Loamy/Sandy'),
('Sage','3','Sage is a hardy perennial with pretty, grayish green leaves that like as good in a perennial border as they do in a vegetable garden. It grows spikes of spring flowers in different colors, including purple, blue, white, and pink. Used both dried and fresh, sage leaves are a popular poultry and meat seasoning. Sage also makes a soothing tea.','plant15.png','Perennial','Full Sun','Zones 4 to 10','Loamy/Sandy'),
('Tomatoes – San Marzano','4','Native to Italy, San Marzano tomatoes are distinctive tomatoes with an oblong shape and a pointed end. This tomato is bright red with thick skin and very few seeds. They grow in clusters of six to eight fruits. Also known as San Marzano sauce tomatoes, the fruit is sweeter and less acidic than standard tomatoes. This provides a unique balance of sweetness and tartness. They are widely used in sauces, pastes, pizza, pasta, and other Italian cuisines.','plant16.png','Annual','Full Sun','Zones 5 to 10','Rich, fertile soil'),
('Squash – Winter Delicata','4','Delicata''s 7"-9" oblong fruit has ivory-colored skin striped with green. Its flesh has a rich, sweet-potato-like flavor which is ideal for baking or stuffing. Its short vines are prolific.','plant17.png','Annual','Full Sun','Zones 8 to 10','Fertile, well-drained'),
('Kale – Lacinato','4','Kale is a cold-hardy crop that can be planted in early spring or late summer. Cool weather brings out the sweet, nutty flavor of this highly nutritious leafy green. Kale is versatile in the garden, growing in traditional beds or raised beds and containers. It’s also versatile in the kitchen and a nutritious addition to salads, stir fries, omelettes, casseroles, and other dishes.','plant18.png','Biennial','Partial Sun','Zones 2 to 8','Loamy'),
('Broccoli – Calabrese','4','Broccoli is a sun-loving, cool-season crop that is best grown in the spring or fall. Broccoli is incredibly healthy and has been dubbed the "crown jewel of nutrition." ','plant19.png','Annual','Full Sun','Zones 3 to 10','Sandy'),
('Pumpkin – Casper','4','White-skinned ornamental pumpkin with thick orange flesh of excellent eating quality. The Casper skin has less bluing than many other white varieties. Handle is tan with a corky texture. 8"-12" diameter, 10-20 pounds, use like squash or for pies.','plant20.png','Annual','Full Sun','Zones 3 to 9','Any');

